runtime: java
env: flex

handlers:
- url: /indocs-server/.*
  script: this field is required, but ignored

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

runtime_config:
   jdk: openjdk8
   server: jetty9

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2